---
title: "Lab book: ML outputs (matrix), spike proteins"
output: radix::radix_article
geometry: margin=1in, includeheadfoot
fig_captions: true
fontsize: 3pt
header-includes:
   - \usepackage{longtable}
   - \usepackage{fancyhdr}
   - \fancyfoot[LE,RO]{\thepage}
author:
  - name: Liam Brierley
    affiliation: University of Liverpool
date: '`r format(Sys.Date(), "%Y-%m-%d")`'
---
\pagenumbering{arabic}

```{r global_options, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE, error=TRUE)

custom_kable <- function(x, caption=NULL) {
   kable(x, caption=caption) %>% kable_styling(font_size = 4, bootstrap_options = c("striped", "hover", "condensed", "responsive"), fixed_thead = T)
}

# Load in previous ML results
#load("listresults_rf_svm_31_05_20.RData")
```

**Summary of CoV host-sharing patterns:**

_Matrices have a 1 if two coronavirus spike sequences were from hosts sharing the taxonomic level specified (e.g. same family), otherwise 0._

From left to right: shared group, species, genus, family, order, class

```{r plot_matrices, results="asis", layout="l-body-outset", fig.height=6.667, fig.width=10.0}
p1 <- grid::rasterGrob(as.raster(png::readPNG("C:\\Users\\Liam\\Desktop\\CoV Genomics\\markdown\\figs\\matrix_cov_spikes_df_group_name.png")),
                           interpolate = FALSE)
p2 <- grid::rasterGrob(as.raster(png::readPNG("C:\\Users\\Liam\\Desktop\\CoV Genomics\\markdown\\figs\\matrix_cov_spikes_df_species_name.png")),
                           interpolate = FALSE)
p3 <- grid::rasterGrob(as.raster(png::readPNG("C:\\Users\\Liam\\Desktop\\CoV Genomics\\markdown\\figs\\matrix_cov_spikes_df_genus_name.png")),
                           interpolate = FALSE)
p4 <- grid::rasterGrob(as.raster(png::readPNG("C:\\Users\\Liam\\Desktop\\CoV Genomics\\markdown\\figs\\matrix_cov_spikes_df_family_name.png")),
                           interpolate = FALSE)
p5 <- grid::rasterGrob(as.raster(png::readPNG("C:\\Users\\Liam\\Desktop\\CoV Genomics\\markdown\\figs\\matrix_cov_spikes_df_order_name.png")),
                           interpolate = FALSE)
p6 <- grid::rasterGrob(as.raster(png::readPNG("C:\\Users\\Liam\\Desktop\\CoV Genomics\\markdown\\figs\\matrix_cov_spikes_df_class_name.png")),
                           interpolate = FALSE)

gridExtra::grid.arrange(p1, p2, p3, p4, p5, p6, ncol = 3)
```